services:

  nginx:
    image: jwilder/nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/le-certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /root/vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - nginx_cache:/cache
      - ${COVER_ART_CACHE_DIR}:/cover-art-cache
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - ssl-proxy-network
        
  le:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/ssl/le-certs:/etc/nginx/certs:rw
      - /root/vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    environment:
      - NGINX_PROXY_CONTAINER=nginx
    networks:
      - ssl-proxy-network

networks:
  ssl-proxy-network:
    name: ssl-proxy-network

volumes:
  nginx_cache:
  html:
